import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets:["latin"],
 
})
export const metadata: Metadata = {
  title: "Create by Jorge Flores Partida",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en,es">
      <body
        className={`${outfit.className} bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
