import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create by Jorge Flores Partida",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${outfit.className} bg-white`}>
        
        {/* 📌 Se carga en TODAS las páginas */}
        <Header />

        {/* 📌 Contenido dinámico */}
        <main className="min-h-screen">
          {children}
        </main>

        {/* 📌 Footer global */}
        <Footer/>

      </body>
    </html>
  );
}
